// Copyright 2025 Icebreak Studios. All rights reserved.

#pragma once

#include "CoreMinimal.h"
#include "GameplayEffect.h"
#include "Engine/DataAsset.h"
#include "PerkData.generated.h"

/**
 * Holds relevant data for metaprogression perks
 *
 * Jeff Stevenson
 * 11.17.25
 */

USTRUCT(BlueprintType)
struct FPerkInfo
{
	GENERATED_BODY()
	
public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString Name;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	FString Description;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	int32 Cost;
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	UGameplayEffect* GameplayEffect;

	// prerequisite system - should like use set of perk ID fields that would be autogenerated in data asset
	// currently unimplemented
	/*UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TSet<FPerkInfo> PrerequisitePerks;

	// TArray requisite overrides
	bool operator==(const FPerkInfo& Other) const
	{
		return Name == Other.Name && Description == Other.Description && Cost == Other.Cost;
	}*/

	// equals and not equals operator implementation
	bool operator==(const FPerkInfo& Other) const
	{
		return Name == Other.Name && Description == Other.Description;
	}

	bool operator!=(const FPerkInfo& Other) const
	{
		return !operator==(Other);
	}
	
	// checks if ability and mapping are both filled for the mapping data
	bool IsValid() const
	{
		return !Name.IsEmpty() && !Description.IsEmpty() && Cost;
	}

	// Hash type pairing for TSet pairing
	friend uint32 GetTypeHash(const FPerkInfo& Perk)
	{
		return HashCombine(GetTypeHash(Perk.Name), GetTypeHash(Perk.Description));
	}
};

UCLASS()
class COLDSNAP_API UPerkData : public UDataAsset
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite)
	TSet<FPerkInfo> Perks;
};
